services:
  nginx:
    ports:
      - "${PORT}:80"
      - 443:443
    environment:
      HOST_URL: ${CERT_DOMAIN}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/template:/etc/nginx/templates/10-variables.conf.template:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static/:/var/www/static/

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx-ssl
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${CERT_EMAIL} --agree-tos --no-eff-email
      -d ${CERT_DOMAIN}
    profiles:
      - production
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
