services:
  nginx:
    ports: !override
      - 80:80
      - 443:443
    environment:
      HOST_URL: ${CERT_DOMAIN}
    volumes:
      - ./certs/certbot:/var/www/certbot
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./nginx/templates/ssl.conf.template:/etc/nginx/templates/ssl.conf.template:ro

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${CERT_EMAIL} --agree-tos --no-eff-email
      -d ${CERT_DOMAIN}
    volumes:
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./certs/certbot:/var/www/certbot
