services:
  nginx:
    ports:
      - 443:443
    volumes: !override
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default-ssl.conf.template:/etc/nginx/conf.d/default-ssl.conf-ssl.conf.template:ro
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./certs/certbot:/var/www/certbot
      - ./static/:/var/www/static/

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${CERT_EMAIL} --agree-tos --no-eff-email
      -d ${CERT_DOMAIN}
    volumes:
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./certs/certbot:/var/www/certbot
