name: Build and Deploy to Staging

on:
  push:
    branches:
      - initialize-ci
    tags:
      - "*"

jobs:
  docker-build:
    name: Docker Build
    runs-on: docker

    steps:
      - name: Checkout Code
        uses: https://github.com/actions/checkout@v4

      - name: Build Docker Image
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true

  deploy:
    name: Deploy to Server
    runs-on: docker
    needs: docker-build

    steps:
      - name: Deploy via SSH
        uses: https://github.com/appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Navigating to the Docker Compose file directory"
            cd /path to your repo/
            echo "Stopping and removing any running containers"
            docker stop <container name>
            docker rm <container name>
            echo "Removing the old Docker image"
            docker rmi -f <latest image>|| true
            echo "Logging into Docker Hub on the remote server"
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "Pulling the latest image"
            docker compose up --build -d
