name: Build and Deploy to Staging

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "**"

jobs:
  changes:
    name: Check for Changes
    runs-on: ubuntu-22.04
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout Code
        uses: https://github.com/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Changes
        id: filter
        uses: https://github.com/dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  check-backend:
    name: Check Backend
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - name: Checkout Code
        uses: https://github.com/actions/checkout@v4

      - name: Auf elegante Weise die Ubuntu Version ermitteln
        run: |
          uname -a
          cat /etc/os-release

      - name: Mich interessiert vorallem die glibc Version
        run: ldd --version

      # - name: Test Stack Project
      #   uses: https://github.com/freckle/stack-action@v5
      #   with:
      #     working-directory: backend
      - name: Check Formatting
        run: |
          cd backend
          curl -sL https://raw.github.com/haskell/stylish-haskell/master/scripts/latest.sh | bash -s -- -r -i .
          if [ -n "$(git status --porcelain)" ]; then
            echo "Found unformatted files:"
            git diff
            exit 1
          fi

      - name: Setup HLint
        uses: https://github.com/haskell-actions/hlint-setup@v2
        with:
          version: "3.10"

      - name: HLint
        uses: https://github.com/haskell-actions/hlint-run@v2
        with:
          path: backend/
          fail-on: suggestion

  check-frontend:
    name: Check Frontend
    runs-on: ubuntu-22.04
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Checkout Code
        uses: https://github.com/actions/checkout@v4

      - name: Setup Node
        uses: https://github.com/actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install PureScript tools
        working-directory: frontend
        run: |
          npm install -g purescript spago@next purs-tidy
          npm install

      - name: Check Formatting
        working-directory: frontend
        run: purs-tidy check .

      - name: Run Tests
        working-directory: frontend
        run: spago test

  tests-pass:
    name: Tests Pass
    runs-on: ubuntu-22.04
    needs:
      - changes
      - check-backend
      - check-frontend
    if: always()
    steps:
      - name: Check all tests pass
        run: |
          # Check dependent jobs...
          RET_CODE=0

          # Only check test jobs if they were supposed to run
          if [[ "${{ needs.changes.outputs.backend }}" == "true" ]]; then
            [[ "${{ needs.check-backend.result }}"       != 'success' ]] && { RET_CODE=1; echo "Backend tests failed"; }
          fi

          if [[ "${{ needs.changes.outputs.frontend }}" == "true" ]]; then
            [[ "${{ needs.check-frontend.result }}"      != 'success' ]] && { RET_CODE=1; echo "Backend tests failed"; }
          fi

          if [[ "$RET_CODE" -eq 0 ]]; then
            echo "All tests passed successfully!"
          fi
          exit $RET_CODE

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-22.04
    needs: [tests-pass]
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 60
    steps:
      - name: Deploy via SSH
        uses: https://github.com/appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 200m
          script: |
            cd ${{ vars.REPO_PATH }}
            git pull
            docker compose -f docker-compose.yaml -f docker-compose.ssl.yaml build
            docker compose down
            docker compose -f docker-compose.yaml -f docker-compose.ssl.yaml up -d
