CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    pwhash TEXT NOT NULL 
);

INSERT INTO
    users (name, email, pwhash)
VALUES
    ('test', 'test@test.com', '123');
