#!/bin/bash
DOCKER_PROFILE="production"
# takes two paramters, the domain name and the email to be associated with the certificate
CERT_DOMAIN=$1
CERT_EMAIL=$2

echo CERT_DOMAIN="${CERT_DOMAIN}" >> .env
echo CERT_EMAIL="${CERT_EMAIL}" >> .env

docker compose -f docker-compose.yaml -f docker-compose.ssl.yaml up -d nginx
docker compose -f docker-compose.yaml -f docker-compose.ssl.yaml up certbot
docker compose down

docker compose -f docker-compose.yaml -f docker-compose.ssl.yaml up -d

echo "Successfully acquired certificates. Consider adding a cronjob for periodic renewal."
